const predictions = [
    "You have blinked. At least once.",
    "You have been born. Weird, right?",
    "You've inhaled air before. Bold move.",
    "You’ve thought about something that didn’t matter.",
    "At some point, you’ve had an itch.",
    "You’ve existed longer than 0 seconds.",
    "You’ve experienced gravity. Multiple times.",
    "You’ve had at least one toe wiggle. Ever.",
    "You’ve been in a room. Possibly more than one.",
    "You’ve seen your reflection and made a face.",
    "You've believed your phone vibrated when it didn’t.",
    "You've looked at a clock and forgot what time it said.",
    "You've accidentally made eye contact with a stranger.",
    "You've thought you lost your phone... while holding it.",
    "You've re-read this list entry twice. Just in case.",
    "You've imagined winning an argument you never had.",
    "You've definitely yawned at some point in your life.",
    "You've sat on something and immediately regretted it.",
    "You've opened the fridge without a mission.",
    "You've felt awkward for no clear reason.",
    "You've avoided a crack in the sidewalk. For luck.",
    "You’ve walked into a room and panicked mentally.",
    "You’ve scrolled aimlessly and liked it.",
    "You’ve breathed manually today. Congrats.",
    "You’ve told a lie about liking someone’s cooking.",
    "You’ve fake laughed at least once in public.",
    "You’ve waved at someone who wasn't waving at you.",
    "You’ve regretted a haircut decision, past or present.",
    "You’ve felt called out by a meme.",
    "You’ve told someone ‘you too’ at the wrong time.",
    "You’ve doubted if ducks are real. Deep down.",
    "You’ve sniffed something questionable. On purpose.",
    "You’ve Googled a symptom and diagnosed yourself fatally.",
    "You’ve worn clothes backwards without noticing (yet).",
    "You’ve heard a song and pretended you didn’t like it.",
    "You’ve walked faster to pretend you’re not being followed.",
    "You’ve been caught singing when you thought you were alone.",
    "You’ve judged someone silently. Multiple times.",
    "You’ve opened 5 tabs and used 1.",
    "You’ve dropped your phone on your face. At least once.",
    "You’ve convinced yourself you locked the door. You didn’t.",
    "You’ve refreshed a feed like it owes you something.",
    "You’ve called your teacher ‘mom’ or ‘dad’. Painfully.",
    "You’ve planned a comeback 3 years too late.",
    "You’ve forgotten why you walked into the kitchen.",
    "You’ve had a staring contest with your own reflection.",
    "You’ve made a fake phone call to escape a conversation.",
    "You’ve regretted sending that emoji. Immediately.",
    "You’ve pretended not to see someone in public.",
    "You’ve said 'I'm fine' while clearly not being fine.",
    "You’ve accidentally refreshed a page and lost everything.",
    "You’ve set multiple alarms and ignored them all.",
    "You’ve tried to discreetly check if someone was looking at you.",
    "You’ve stared at the microwave for the last 3 seconds.",
    "You’ve opened Google with no idea what you needed.",
    "You’ve zoned out mid-conversation and nodded anyway.",
    "You’ve used 'LOL' without actually laughing.",
    "You’ve faked typing to avoid replying too fast.",
    "You’ve left something in the oven just a bit too long.",
    "You’ve hit 'Remind me tomorrow' for weeks.",
    "You’ve talked to yourself and answered back.",
    "You’ve Googled the spelling of a basic word.",
    "You’ve re-read a message 3 times before replying.",
    "You’ve sent a risky text and instantly regretted it.",
    "You’ve walked into a spiderweb and fought a ghost.",
    "You’ve stood up too fast and saw another dimension.",
    "You’ve pretended to be on the phone to avoid someone.",
    "You’ve checked if the shampoo is actually working.",
    "You’ve cleaned one corner and called it a day.",
    "You’ve left a shopping cart in the middle of the aisle.",
    "You’ve apologized to an object you bumped into.",
    "You’ve pretended to understand a reference.",
    "You’ve laughed because others were laughing.",
    "You’ve felt proud after catching something mid-air.",
    "You’ve skipped an ad and felt powerful.",
    "You’ve stared at your screen like it betrayed you.",
    "You’ve gone to YouTube for one video. Two hours later…",
    "You’ve hesitated before spelling ‘necessary’.",
    "You’ve responded ‘you too’ to a ‘happy birthday’.",
    "You’ve scrolled past something important and lost it forever.",
    "You’ve read one paragraph 4 times and absorbed none.",
    "You’ve used ‘lol’ to soften emotional breakdowns.",
    "You’ve blamed autocorrect for your typing chaos.",
    "You’ve eaten something just to avoid wasting it.",
    "You’ve said ‘I'm on my way’ while not even dressed.",
    "You’ve closed a tab dramatically after rage-searching.",
    "You’ve scrolled past spoilers with reflexes of a ninja.",
    "You’ve stayed in the shower just to avoid responsibilities.",
    "You’ve sung a song wrong for years. Proudly.",
    "You’ve felt pain after stubbing your toe and questioned life.",
    "You’ve looked at your phone with no notifications anyway.",
    "You’ve wished someone would text you, then ignored them.",
    "You’ve memorized a fake laugh for specific situations.",
    "You’ve used sarcasm as a love language.",
    "You’ve opened a text and instantly forgotten to reply.",
    "You’ve felt hunger but too lazy to move.",
    "You’ve taken a break during a break.",
    "You’ve typed 'haha' to cover emotional damage.",
    "You’ve said 'I’ll do it later' about everything today.",
    "You’ve whispered 'what?' when alone and confused."
];
const x = Math.floor(Math.random() * predictions.length);
document.getElementById("main").innerHTML = predictions[x];
